name: Laravel Testing workflow

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

jobs:
      
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout

        uses: actions/checkout@v2
    
  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout

        uses: actions/checkout@v2

      - name: Deployment

        uses: appleboy/ssh-action@master

        with:

          host: ${{ secrets.SSH_HOST }}

          key: ${{ secrets.SSH_PRIVATE_KEY }}

          username: ${{ secrets.SSH_USERNAME }}

          script: |

            cd /var/www/html/laravel2

            git checkout -f 
            
            git pull https://github.com/PritomD/laravel test --allow-unrelated-histories